services:
  # VROOM routing engine service
  vroom:
    build:
      context: ./docker/vroom
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VROOM_PORT=3000
      - OSRM_URL=http://osrm:5000
    volumes:
      - ./docker/vroom/config:/app/config
    networks:
      - tradeflow-network
    depends_on:
      - osrm

  # OSRM routing engine service - Real backend for production routing
  osrm:
    image: osrm/osrm-backend:latest
    ports:
      - "5001:5000"
    volumes:
      - ./docker/osrm/data:/data
    command: osrm-routed --algorithm mld /data/north-america-latest.osrm
    networks:
      - tradeflow-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/nearest/v1/driving/-122.4194,37.7749"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  tradeflow-network:
    driver: bridge 